SELECT S.SID, P.COLOR FROM SUPPLIERS AS S
	JOIN `CATALOG` AS C ON S.SID = C.SID
	JOIN PARTS AS P ON C.PID = P.PID
WHERE P.COLOR = 'green' AND P.COLOR = 'red';




SELECT P.COLOR, S.SID, P.PID FROM SUPPLIERS AS S
	JOIN `CATALOG` AS C ON S.SID = C.SID
	JOIN PARTS AS P ON C.PID = P.PID
WHERE P.COLOR = 'red' or P.COLOR = 'green'
GROUP BY P.COLOR, P.PID, S.SID
ORDER BY P.COLOR, S.SID;


select PID, COLOR
FROM PARTS
WHERE COLOR = 'red';

INSERT INTO `CATALOG` (`SID`,`PID`,`COST`) VALUES (123,109,"$23.78");