insert into public.parts (pid, pname, color) values (1, 'Sherry - Dry', 'Khaki');
insert into public.parts (pid, pname, color) values (2, 'Yogurt - Plain', 'Khaki');
insert into public.parts (pid, pname, color) values (3, 'Soup - Campbells - Tomato', 'Fuscia');
insert into public.parts (pid, pname, color) values (4, 'Sobe - Lizard Fuel', 'Green');
insert into public.parts (pid, pname, color) values (5, 'Spice - Pepper Portions', 'Purple');
insert into public.parts (pid, pname, color) values (6, 'Oil - Olive', 'Puce');
insert into public.parts (pid, pname, color) values (7, 'Nut - Hazelnut, Ground, Natural', 'Violet');
insert into public.parts (pid, pname, color) values (8, 'Beef - Tender Tips', 'Blue');
insert into public.parts (pid, pname, color) values (9, 'Bread - Bistro White', 'Violet');
insert into public.parts (pid, pname, color) values (10, 'Snapple - Mango Maddness', 'Goldenrod');
insert into public.parts (pid, pname, color) values (11, 'Jam - Raspberry', 'Puce');
insert into public.parts (pid, pname, color) values (12, 'Pail - 4l White, With Handle', 'Goldenrod');
insert into public.parts (pid, pname, color) values (13, 'Wine - Red, Pinot Noir, Chateau', 'Puce');
insert into public.parts (pid, pname, color) values (14, 'Watercress', 'Indigo');
insert into public.parts (pid, pname, color) values (15, 'Guinea Fowl', 'Aquamarine');
insert into public.parts (pid, pname, color) values (16, 'Cup - 3.5oz, Foam', 'Goldenrod');
insert into public.parts (pid, pname, color) values (17, 'Puff Pastry - Slab', 'Pink');
insert into public.parts (pid, pname, color) values (18, 'Pasta - Cheese / Spinach Bauletti', 'Puce');
insert into public.parts (pid, pname, color) values (19, 'Coffee Decaf Colombian', 'Purple');
insert into public.parts (pid, pname, color) values (20, 'Dried Cranberries', 'Goldenrod');
insert into public.parts (pid, pname, color) values (21, 'Juice - Lime', 'Goldenrod');
insert into public.parts (pid, pname, color) values (22, 'Flour - Bran, Red', 'Aquamarine');
insert into public.parts (pid, pname, color) values (23, 'Pears - Bosc', 'Aquamarine');
insert into public.parts (pid, pname, color) values (24, 'Beef - Rib Roast, Capless', 'Violet');
insert into public.parts (pid, pname, color) values (25, 'Beef - Roasted, Cooked', 'Indigo');
insert into public.parts (pid, pname, color) values (26, 'Cup - 4oz Translucent', 'Khaki');
insert into public.parts (pid, pname, color) values (27, 'Ecolab - Lime - A - Way 4/4 L', 'Maroon');
insert into public.parts (pid, pname, color) values (28, 'Pepper - Red Chili', 'Mauv');
insert into public.parts (pid, pname, color) values (29, 'Clementine', 'Goldenrod');
insert into public.parts (pid, pname, color) values (30, 'Oil - Macadamia', 'Turquoise');
insert into public.parts (pid, pname, color) values (31, 'Juice - Orange 1.89l', 'Orange');
insert into public.parts (pid, pname, color) values (32, 'Cabbage - Savoy', 'Red');
insert into public.parts (pid, pname, color) values (33, 'Straw - Regular', 'Green');
insert into public.parts (pid, pname, color) values (34, 'Crab - Soft Shell', 'Mauv');
insert into public.parts (pid, pname, color) values (35, 'Island Oasis - Lemonade', 'Crimson');
insert into public.parts (pid, pname, color) values (36, 'Fish - Atlantic Salmon, Cold', 'Yellow');
insert into public.parts (pid, pname, color) values (37, 'Island Oasis - Pina Colada', 'Fuscia');
insert into public.parts (pid, pname, color) values (38, 'Flavouring - Rum', 'Pink');
insert into public.parts (pid, pname, color) values (39, 'Boogies', 'Indigo');
insert into public.parts (pid, pname, color) values (40, 'Garbage Bags - Black', 'Fuscia');
insert into public.parts (pid, pname, color) values (41, 'Chocolate - Sugar Free Semi Choc', 'Green');
insert into public.parts (pid, pname, color) values (42, 'Napkin - Beverage 1 Ply', 'Goldenrod');
insert into public.parts (pid, pname, color) values (43, 'True - Vue Containers', 'Maroon');
insert into public.parts (pid, pname, color) values (44, 'Bread - Assorted Rolls', 'Aquamarine');
insert into public.parts (pid, pname, color) values (45, 'Alize Sunset', 'Fuscia');
insert into public.parts (pid, pname, color) values (46, 'Table Cloth 54x54 Colour', 'Maroon');
insert into public.parts (pid, pname, color) values (47, 'Appetizer - Mango Chevre', 'Indigo');
insert into public.parts (pid, pname, color) values (48, 'Coconut - Shredded, Unsweet', 'Puce');
insert into public.parts (pid, pname, color) values (49, 'Ice Cream Bar - Hageen Daz To', 'Crimson');
insert into public.parts (pid, pname, color) values (50, 'Piping - Bags Quizna', 'Indigo');
insert into public.parts (pid, pname, color) values (51, 'Foam Espresso Cup Plain White', 'Maroon');
insert into public.parts (pid, pname, color) values (52, 'Cream - 35%', 'Purple');
insert into public.parts (pid, pname, color) values (53, 'Country Roll', 'Mauv');
insert into public.parts (pid, pname, color) values (54, 'Venison - Racks Frenched', 'Violet');
insert into public.parts (pid, pname, color) values (55, 'Bread - Roll, Calabrese', 'Goldenrod');
insert into public.parts (pid, pname, color) values (56, 'Venison - Ground', 'Aquamarine');
insert into public.parts (pid, pname, color) values (57, 'Yukon Jack', 'Pink');
insert into public.parts (pid, pname, color) values (58, 'Sauce - Balsamic Viniagrette', 'Violet');
insert into public.parts (pid, pname, color) values (59, 'Bandage - Finger Cots', 'Orange');
insert into public.parts (pid, pname, color) values (60, 'Cheese - Grana Padano', 'Purple');
insert into public.parts (pid, pname, color) values (61, 'Bread - Raisin Walnut Pull', 'Yellow');
insert into public.parts (pid, pname, color) values (62, 'Soup - Campbells, Chix Gumbo', 'Teal');
insert into public.parts (pid, pname, color) values (63, 'Cake - Mini Potato Pancake', 'Orange');
insert into public.parts (pid, pname, color) values (64, 'Beans - Navy, Dry', 'Goldenrod');
insert into public.parts (pid, pname, color) values (65, 'Crab - Claws, Snow 16 - 24', 'Crimson');
insert into public.parts (pid, pname, color) values (66, 'Milk - Condensed', 'Orange');
insert into public.parts (pid, pname, color) values (67, 'Bread - Flat Bread', 'Yellow');
insert into public.parts (pid, pname, color) values (68, 'Cheese - Romano, Grated', 'Violet');
insert into public.parts (pid, pname, color) values (69, 'Salmon Steak - Cohoe 6 Oz', 'Teal');
insert into public.parts (pid, pname, color) values (70, 'Longos - Grilled Salmon With Bbq', 'Pink');
insert into public.parts (pid, pname, color) values (71, 'Extract - Raspberry', 'Puce');
insert into public.parts (pid, pname, color) values (72, 'Beans - Black Bean, Dry', 'Violet');
insert into public.parts (pid, pname, color) values (73, 'Pear - Prickly', 'Violet');
insert into public.parts (pid, pname, color) values (74, 'Oil - Macadamia', 'Puce');
insert into public.parts (pid, pname, color) values (75, 'Appetizer - Shrimp Puff', 'Purple');
insert into public.parts (pid, pname, color) values (76, 'Hinge W Undercut', 'Puce');
insert into public.parts (pid, pname, color) values (77, 'Ginger - Pickled', 'Maroon');
insert into public.parts (pid, pname, color) values (78, 'Nantucket - 518ml', 'Pink');
insert into public.parts (pid, pname, color) values (79, 'Tomato - Plum With Basil', 'Khaki');
insert into public.parts (pid, pname, color) values (80, 'Tomato - Green', 'Turquoise');
insert into public.parts (pid, pname, color) values (81, 'Eggroll', 'Aquamarine');
insert into public.parts (pid, pname, color) values (82, 'Chickhen - Chicken Phyllo', 'Green');
insert into public.parts (pid, pname, color) values (83, 'Sprite - 355 Ml', 'Teal');
insert into public.parts (pid, pname, color) values (84, 'The Pop Shoppe - Root Beer', 'Pink');
insert into public.parts (pid, pname, color) values (85, 'Danishes - Mini Raspberry', 'Aquamarine');
insert into public.parts (pid, pname, color) values (86, 'Wine - Magnotta - Red, Baco', 'Pink');
insert into public.parts (pid, pname, color) values (87, 'Soup Campbells Mexicali Tortilla', 'Teal');
insert into public.parts (pid, pname, color) values (88, 'Calypso - Pineapple Passion', 'Goldenrod');
insert into public.parts (pid, pname, color) values (89, 'Carbonated Water - Raspberry', 'Indigo');
insert into public.parts (pid, pname, color) values (90, 'Quail - Whole, Boneless', 'Puce');
insert into public.parts (pid, pname, color) values (91, 'Steel Wool S.o.s', 'Fuscia');
insert into public.parts (pid, pname, color) values (92, 'Sansho Powder', 'Teal');
insert into public.parts (pid, pname, color) values (93, 'Table Cloth 81x81 Colour', 'Teal');
insert into public.parts (pid, pname, color) values (94, 'Bok Choy - Baby', 'Teal');
insert into public.parts (pid, pname, color) values (95, 'Soup - Knorr, Veg / Beef', 'Maroon');
insert into public.parts (pid, pname, color) values (96, 'Pasta - Cheese / Spinach Bauletti', 'Yellow');
insert into public.parts (pid, pname, color) values (97, 'Flour - Pastry', 'Pink');
insert into public.parts (pid, pname, color) values (98, 'Sparkling Wine - Rose, Freixenet', 'Maroon');
insert into public.parts (pid, pname, color) values (99, 'Cheese - Bocconcini', 'Crimson');
insert into public.parts (pid, pname, color) values (100, 'Turkey - Whole, Fresh', 'Teal');
insert into public.parts (pid, pname, color) values (200, 'green par', 'green');
insert into public.parts (pid, pname, color) values (201, 'red part', 'red');
