create table SUPPLIERS (
	SID INT,
	SNAME VARCHAR(100),
	ADDRESS VARCHAR(100),
	PRIMARY KEY (SID)
);
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (1, 'Hovnanian Enterprises Inc', 'Āgaro');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (2, 'CubeSmart', 'Kebonsari');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (3, 'TechnipFMC plc', 'Comrat');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (4, 'Schweitzer-Mauduit International, Inc.', 'Cruzeiro');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (5, 'Grupo Supervielle S.A.', 'Lota');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (6, 'New Media Investment Group Inc.', 'Mardīān');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (7, 'BlackRock New York Investment Quality Municipal Trust Inc. (Th', 'Strabychovo');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (8, 'AxoGen, Inc.', 'Askeaton');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (9, 'Uranium Resources, Inc.', 'Basud');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (10, 'Dorian LPG Ltd.', 'Igpit');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (11, 'Pioneer Natural Resources Company', 'Cruzeiro');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (12, 'Arbor Realty Trust', 'Riberalta');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (13, 'Western Gas Partners, LP', 'Cikadongdong');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (14, 'Genesis Energy, L.P.', 'Jerusalem');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (15, 'Nuveen New York AMT-Free Quality Municipal', 'Machetá');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (16, 'DMC Global Inc.', 'Bagok');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (17, 'Fate Therapeutics, Inc.', 'Njivice');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (18, 'CBS Corporation', 'Крушопек');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (19, 'QEP Resources, Inc.', 'Dagestanskiye Ogni');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (20, 'Yamana Gold Inc.', 'Saint-Lô');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (21, 'Verint Systems Inc.', 'Cheping');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (22, 'Luna Innovations Incorporated', 'Maji');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (23, 'Estee Lauder Companies, Inc. (The)', 'Krajan Jamprong');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (24, 'Atlantic Coast Financial Corporation', 'Grindavík');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (25, 'Sound Financial Bancorp, Inc.', 'Dahu');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (26, 'Stemline Therapeutics, Inc.', 'Tours');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (27, 'Bank of America Corporation', 'Leuwidamar');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (28, 'Cardiovascular Systems, Inc.', 'Níkiti');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (29, 'Spark Therapeutics, Inc.', 'Daqingshan');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (30, 'PNC Financial Services Group, Inc. (The)', 'Alvesta');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (31, 'Tower Semiconductor Ltd.', 'Kotlovka');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (32, 'Middlefield Banc Corp.', 'Matam');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (33, 'Nuveenn Intermediate Duration Quality Municipal Term Fund', 'Pandanrejokrajan');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (34, 'The Goodyear Tire & Rubber Company', 'Xicun');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (35, 'Royal Bank Scotland plc (The)', 'Bor');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (36, 'Barclays PLC', 'Mantalongon');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (37, 'Geo Group Inc (The)', 'Herne');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (38, 'Haverty Furniture Companies, Inc.', 'Croix');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (39, 'RADA Electronic Industries Ltd.', 'Ubay');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (40, 'Bay Bancorp, Inc.', 'Ferraz de Vasconcelos');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (41, 'Matson, Inc.', 'Dongqianhu');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (42, 'VeriSign, Inc.', 'Honda');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (43, 'Corium International, Inc.', 'Ciakar');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (44, 'voxeljet AG', 'Częstochowa');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (45, 'Aeglea BioTherapeutics, Inc.', 'Huangtan');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (46, 'Investors Real Estate Trust', 'Xingcheng');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (47, 'Healthcare Realty Trust Incorporated', 'Shreveport');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (48, 'Exactech, Inc.', 'Shijiazhai');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (49, 'Sorrento Therapeutics, Inc.', 'Katsina');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (50, 'TIM Participacoes S.A.', 'Jetis');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (51, 'Varian Medical Systems, Inc.', 'Cuijiamatou');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (52, 'Varonis Systems, Inc.', 'El Quebrachal');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (53, 'Incyte Corporation', 'Balogo');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (54, 'Century Casinos, Inc.', 'Stupino');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (55, 'Aspen Insurance Holdings Limited', 'Vukatanë');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (56, 'Premier Financial Bancorp, Inc.', 'Zavidovo');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (57, 'James River Group Holdings, Ltd.', 'Tétouan');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (58, 'United Community Banks, Inc.', 'Tampa');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (59, 'Cognex Corporation', 'Saint-Denis');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (60, 'Legg Mason, Inc.', 'Round Rock');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (61, 'Kenon Holdings Ltd.', 'Liutangting');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (62, 'Stock Yards Bancorp, Inc.', 'Chikeng');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (63, 'Home Depot, Inc. (The)', 'Jianfeng');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (64, 'NexPoint Residential Trust, Inc.', 'Tabuaço');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (65, 'Stone Energy Corporation', 'Volzhsk');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (66, 'Telephone and Data Systems, Inc.', 'Turpo');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (67, 'Renren Inc.', 'Khromtau');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (68, 'USANA Health Sciences, Inc.', 'Jiahe');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (69, 'Dominion Energy, Inc.', 'Al Hadā');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (70, 'JAKKS Pacific, Inc.', 'Renliu');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (71, 'Vornado Realty Trust', 'Bakar');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (72, 'TheStreet, Inc.', 'Kaminokawa');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (73, 'Allison Transmission Holdings, Inc.', 'Tupanciretã');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (74, 'Illumina, Inc.', 'Horvati');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (75, 'Tractor Supply Company', 'Springfield');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (76, 'Summit State Bank', 'Sampungu');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (77, 'MFA Financial, Inc.', 'Dédougou');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (78, 'Quest Diagnostics Incorporated', 'Nyzhni Sirohozy');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (79, 'McCormick & Company, Incorporated', 'Cipanas');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (80, 'Prosperity Bancshares, Inc.', 'Troyes');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (81, 'Double Eagle Acquisition Corp.', 'Saint-Fargeau-Ponthierry');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (82, 'Jernigan Capital, Inc.', 'Rambatan');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (83, 'Nuveen Senior Income Fund', 'Luksuhin');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (84, 'Cross Timbers Royalty Trust', 'Białogard');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (85, 'Blackrock MuniYield California Fund, Inc.', 'Sumbergayam');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (86, 'Franco-Nevada Corporation', 'Auas');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (87, 'Verint Systems Inc.', 'Tsurugi-asahimachi');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (88, 'Fox Factory Holding Corp.', 'Mairana');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (89, 'Legacy Reserves LP', 'Kambar');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (90, 'DragonWave Inc', 'Jiangchang');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (91, 'CF Corporation', 'Huddinge');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (92, 'BioDelivery Sciences International, Inc.', 'Wichita');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (93, 'Automatic Data Processing, Inc.', 'Seversk');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (94, 'Meridian Waste Solutions, Inc', 'Vargem Grande');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (95, 'Integer Holdings Corporation', 'Raša');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (96, 'El Paso Corporation', 'Cergy-Pontoise');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (97, 'Corcept Therapeutics Incorporated', 'Jaroměř');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (98, 'Pitney Bowes Inc.', 'Huangcai');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (99, 'Winnebago Industries, Inc.', 'Seka');
insert into SUPPLIERS (SID, SNAME, ADDRESS) values (100, 'CBS Corporation', 'Caieiras');
